FROM node:18 AS build

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . ./
RUN npm run build

EXPOSE 5000

CMD ["npm", "start"]

# FROM nginx:1.24.0-alpine
# COPY --from=build /app/public /usr/share/nginx/html